apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
        - name: samplewebapp 
          image: sriniacr44.azurecr.io/samplewebapp
          ports:
          - containerPort: 80
- name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: game-demo
      # An array of keys from the ConfigMap to create as files
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"
